### ISSUE TITLE
parsing issue?

### ISSUE THREAD

**Issue by deccer** [TheComet/GLaDOS2#79]
```python
**An exception occurred while processing a message:**
Traceback (most recent call last):
  File "/home/cometbot/discord/GLaDOS2/glados/bot.py", line 230, in __message_processor
    await self.server_instances[message.server.id].process_message(message)
  File "/home/cometbot/discord/GLaDOS2/glados/bot.py", line 197, in process_message
    await callback(message, content)
  File "modules/general/log.py", line 35, in on_message
    self.log_file.write(info)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f603' in position 95: ordinal not in range(128)
```

after saying `introduced new classes today already? 😃` in our programming channel, glados texted me the aforementioned stacktrace

https://i.imgur.com/j0g4YUR.png

**Comment by deccer** [comment]
Glados doesn't like smileys. It craps out on `:)`  and `:(` and possibly on other emoji's too
